set(SRC_FILES
    App.cpp
    Character.cpp
    DonkeyKong.cpp
    Fiamma.cpp
    HUDManager.cpp
    Mario.cpp
    Barrel.cpp
    Map.cpp
    LevelData.cpp
    Elevator.cpp
    OpeningScene.cpp
)

set(INCLUDE_FILES
    App.hpp
    AnimatedCharacter.hpp
    Character.hpp
    DonkeyKong.hpp
    Fiamma.hpp
    HUDManager.hpp
    Mario.hpp
    Barrel.hpp
    Map.hpp
    LevelData.hpp
    TileType.hpp
    Elevator.hpp
    CementPan.hpp
    CementSpawner.hpp
    ConveeyorSystem.hpp
    OpeningScene.hpp
)

set(TEST_FILES
)
